.gitignore, pisi/fetcher.py, po/ca.po, po/de.po, po/es.po, po/fr.po, po/hr.po, po/hu.po, po/it.po, po/nl.po, po/pisi.pot, po/pl.po, po/pt_BR.po, po/ru.po, po/sv.po, po/tr.po, po/uk.po
urllib2 is part of the standard python library which reduces the amount of moving parts eopkg relies on
It also means we can dropkick python-urlgrabber from the solus repo.
This commit was originally taken from [PiSi](https://github.com/pisilinux/pisi/commit/5e996cfe2c29b5448b5ec7bd3e113ba5c89ddf9a) and rewritten for urllib2.
=> fetcher: Replace urlgrabber usage with urllib2

pisi/constants.py, pisi/operations/build.py
Ever since the retry mechanism was added to pisi/eopkg the install steps for a third party package lead to the following errors:
```
Failed to fetch file, retrying 1 out of 5 "https://raw.githubusercontent.com/getsolus/3rd-party/master/network/web/browser/google-chrome-stable/translations.xml": HTTP Error 404: Not Found
Failed to fetch file, retrying 2 out of 5 "https://raw.githubusercontent.com/getsolus/3rd-party/master/network/web/browser/google-chrome-stable/translations.xml": HTTP Error 404: Not Found
Failed to fetch file, retrying 3 out of 5 "https://raw.githubusercontent.com/getsolus/3rd-party/master/network/web/browser/google-chrome-stable/translations.xml": HTTP Error 404: Not Found
Failed to fetch file, retrying 4 out of 5 …
```
=> Remove "translations.xml" checking from pisi

pisi/configfile.py
> This changes `--param ssp-buffer-size=32` into `--param=ssp-buffer-size=32` (with a connecting equals sign).
> Some configure scripts seem to have a problem with the space in between.
We previously included this patch directly with our Solus package, but it got swept up in the huge patch removal after the recent new tagged release, and I never actually submitted it as a PR before.
More details see [here](https://dev.getsol.us/D8797)
While `anki` no longer seems to suffer from this particular issue, it might pop up somewhere else in the future (or in a rebuild of a currently available package).
P.S. This also matches [the way Ubuntu formats the flag now](https://wiki.ubuntu.com/ToolChain/CompilerFlags#A-fstack-protector-strong_--param.3Dssp-buffer-size.3D4)
=> Make standard C(XX)FLAGS more robust

pisi/util.py
Eopkg currently calculates "binary byte" units (KiB, MiB,....) but shows them as decimal power units (KB, MB,....)
See this discussion: https://discuss.getsol.us/d/6834-difference-between-software-center-and-terminal-update/19
This changes the calculation accordingly so it corresponds to the units shown to the user.
[Seems like I accidentally posted this PR in the wrong repository back in the day ^^ https://github.com/solus-project/package-management/pull/34]
=> Fix download size unit calculation

pisi/__init__.py
Following commit a1f4e9cd6fab55405d28738bddc7d5c46222d4c2, eopkg crashes when solus-sc calls it via d-bus. There's no translation environment in such case. So, when no .mo files are found, just set `translate` to a parrot function.
Thanks to @Staudey and @joebonrichie for finding the bug.
=> pisi/__init__.py: Do not crash when there are no .mo files

eopkg-cli, po/ca.po, po/de.po, po/es.po, po/fr.po, po/hr.po, po/hu.po, po/it.po, po/nl.po, po/pisi.pot, po/pl.po, po/pt_BR.po, po/ru.po, po/sv.po, po/tr.po, po/uk.po
The bug URL for unhandled internal exceptions still points to Pardus.
Granted it shouldn't happen too often, but we don't want to bother them with our bugs :)
=> Update bug URL

pisi/configfile.py
Sources now live at sources.getsol.us instead
=> Update source fallback URL

pisi/cli/history.py
When `less` terminates, modern versions of subprocess close the pipe automatically. This results in a BrokenPipeError if `less` exits before the user reaches EOF.
This PR checks to see if the process is still running before trying to close the pipe, which stops the exception.
=> Fix broken pipe on eopkg hs

pisi/package.py
PiSi currently emits events for other operations e.g. removing,
installing; but crucially not for downloading packages.
This is needed for packagekit so we can get a callback to know when
the package is downloading in order to emit transaction events from
a pisi.api.install call for example.
=> package: emit event when a package is downloading/cached (python3)

pisi/package.py
PiSi currently emits events for other operations e.g. removing,
installing; but crucially not for downloading packages.
This is needed for packagekit so we can get a callback to know when
the package is downloading in order to emit transaction events from
a pisi.api.install call for example.
=> package: emit event when a package is downloading/cached

pisi/actionsapi/shelltools.py, pisi/file.py, pisi/operations/build.py, pisi/pxml/xmlfile.py
This PR fixes a couple of porting errors which were preventing `eopkg build` from working.
=> pisi/operations/build: Make eopkg build work properly

pisi/pxml/xmlfile.py
Fixes `eopkg info --xml`, for example. Previously, if `writexmlfile` was passed a `pisi.file.File` (per the type hint), it would work. If, however, it was passed (say) `sys,stdout`, like `--xml` output does, you would get a TypeError. 
This PR makes `writexmlfile` cast the output of `xml.tostring()` to a `str` before writing to `file`, if `file` is a `_io.TextIOWrapper` (like sys.stdout).
=> pxml/xmlfile: Cast to string before writing to stdout

pisi/file.py, pisi/pxml/xmlfile.py
This PR uses lzma and bz2 in text mode rather than binary mode, so they accept the `str` of xml that's being written out.
=> pisi/file: Use compression libraries in text mode

pisi/pxml/xmlfile.py
This uses an indent level of 4 spaces rather than 2 when formatting XML output such as the index, `--xml` output, and `pspec.xml` from `ypkg`. Piksemel used 4 spaces, while lxml defaults to 2. This change will avoid a lot of noise in the monorepo as packages are rebuild using new tooling.
=> pxml/xmlfile: Indent by 4 spaces when writing XML out

pisi/archive.py
This is done at the last possible moment before interfacing with the py3 standard library tarfile.py module to keep pisi py3 changes to a minimum.
Lucky for us, it was enough to simply re-encode the decoded-to-latin-1 file_name string to utf-8, which the tarfile.py module can then successfully handle.
The bug was exposed by the usdx package.yml, which includes filenames with umlauts in them that tarfile.py would choke on prior to this commit.
**Test Plan:**
1) clone/update the ypkg.git repo
2) run `./prepare_ypkg_test_venv.sh`
3) check that the venv is active!
4) `git -C ../eopkg/ checkout python3-utf8-filename-decoding`
5) Install needed usdx deps locally with something like:
`sudo ./ypkg-install-deps ../soluspkgs/packages/u/usdx/package.yml`
6) Test the usdx package build with something …
=> archive.py: Re-encode file_name object to utf-8

pisi/atomicoperations.py, pisi/files.py, pyproject.toml
I re-applied an ancient commit from @ikeycode and ported it to Python 3.
Note that to build this with Nuitka requires that python-xattr (not in the repo yet, I'll do that shortly) is built with xattr/xattr#119 due to python-cffi limitations.
=> (py3) Add extended attributes support, from base64 encoded key/value pairs

pisi/atomicoperations.py, pisi/files.py
This is literally just Ikey's old commit unedited. It applied cleanly and worked so I didn't touch it.
=> (py2) Add extended attributes support, from base64 encoded key/value pairs

pisi/db/lazydb.py
This enables python2 pisi to read pickle caches created by python3 eopkg.
**Test Plan**
sudo ./eopkg-cli --force update-repo
sudo ./eopkg-cli rdb
sudo ./eopkg-cli info pisi
sudo eopkg-cli info pisi
=> Explicitly set pickle.dump protocol to version 2

eopkg_build.py, pyproject.toml
This allows installing eopkg to a venv for testing using `pip install .`
=> Fix errors in our build system

pisi/operations/build.py
generator.next() is no longer valid in Python 3
bytes object has to be decoded to string before use
This fixes build issues for the third party repo scripts for "Android Studio", "Insync"; and, slightly more importantly, `pisi` itself.
Part of https://github.com/getsolus/3rd-party/issues/78
=> build.py: fix issues with os.walk() and bytes/string encoding

pisi/operations/helper.py, pisi/operations/history.py, pisi/operations/install.py, pisi/operations/upgrade.py
This will ensure that future upgrades to eopkg and baselayout will always happen in a (semi-)deterministic fashion.
- If eopkg is part of the install or upgrade transaction, eopkg will be moved to the front of the transaction.
- If baselayout is part of the install or upgrade transaction, baselayout will be moved to the front of the transaction (possibly in front of eopkg).
For context, only the ordering between eopkg, baselayout and any system.base packages which are part of the transaction is currently preserved.
**How to use this branch as a daily driver for testing**
- (git clone the eopkg repo somewhere) / `git pull -a`
- `git checkout py3-eopkg-and-baselayout-install-upgrade-order
- Add the following function (or its equivalent) to your shell startup scripts:
```bash
function eopkg …
```
=> Py3: Deterministic install/upgrade order for eopkg & baselayout

pisi/__init__.py
... because I forgot to bump to v3.12 for the v3.12 release. ._.
=> pisi: Bump version to v3.12.1

pisi/__init__.py
... because I forgot to bump to v4.1.0 for the v4.1.0 release. ._.
=> eopkg: Bump version to v4.1.1

pisi/operations/check.py
Handle the case with `eopkg check` where the top-level directory has been converted to a symlink and the files were reporting as corrupted.
=> Fix usr-merge file checking

build_chroot.sh, eopkg_venv_functions.bash, pisi/operations/helper.py
We now use OrderedSets, which keep the original topological sort, so this shouldn't actually be necessary now.
This also implies that the only function of system.base is for the packages in it to be un-removable.
NB: This change is _experimental_ and will need loads of upgrade testing!
=> Stop putting system.base at the front of the order

pisi/archive.py, pisi/atomicoperations.py, pisi/package.py, pisi/usr_merge.py
This PR adds support for usr merged paths to the installation and removal functionality.
This change has a performance impact when installing larger packages because the list of files needs to be known when unpacking archives. For `linux-firmware` (a fairly large package) this increases the installation from 5.7s to 8.7s. The list of files known to the package is passed to the tar to mitigate this for the most common case.
=> Add handling for usr merged paths

pisi/archive.py, pisi/atomicoperations.py, pisi/package.py, pisi/usr_merge.py
This PR is a backport of #78. It adds support for usr merged paths to the installation and removal functionality.
This change has a performance impact when installing larger packages because the list of files needs to be known when unpacking archives. The list of files known to the package is passed to the tar to mitigate this for the most common case.
=> Add handling for usr merged paths (python2)

pisi/__init__.py, pisi/operations/helper.py, pisi/operations/install.py, pisi/operations/upgrade.py
With this change, eopkg being in the upgrade order with an associated glibc update will no longer force pisi to abort the transaction due to eopkg showing unfilled dependencies.
=> pisi: Stop re-ordering eopkg for installs/upgrades

pisi/archive.py
Fixes https://github.com/getsolus/3rd-party/issues/81
So this is just a workaround because I'm not familiar with the code at all and don't know why a None fileobj propagates there
https://github.com/getsolus/eopkg/pull/81 doesn't change the behaviour mentioned in above issue
=> Fix 3rd-party build failures for JetBrain IDEs (python2)

pisi/db/filesdb.py, pisi/db/lazydb.py
This is to make it more obvious in the code what pickle protocol version a given pisi cache_version LazyDB file or FilesDB `files.db` database file will be written with.
=> eopkg.py2: Add explicit LazyDB and FilesDB pickle_protocol_version defaults

pisi/db/filesdb.py
This reverts commit 7aab9830e35a4770a28589a633fad11c51af8529, reversing changes made to 311e855cef6430547755c05d3e6412e0f7f727c3.
If the file didn't exist it would never get written.
=> Revert "Merge pull request #41 from getsolus/filesdbornotdb"

pisi/archive.py
This is a port of #83 for python3.
=> Fix exception when building certain pspec.xml files (python3)

README.md, pisi/__init__.py, pisi/api.py, pisi/db/filesdb.py, pisi/db/lazydb.py
The goal is to prototype auto-regeneration of a gdbm backed shelve in eopkg.py2.
Once we're happy with the logic, we can implement similar logic for eopkg.py3 (see #89), thus enabling us to switch back and forth between versions and having the FilesDB cache auto-regenerated on demand.
eopkg.py2 sets `pisi/db/filesdb.FILESDB_FORMAT_VERSION = 3` manually.
**Test Plan**
Non-root `./eopkg.py2` behaviour:
1. _No FilesDB_: `sudo rm /var/lib/eopkg/info/files.db* ; time ./eopkg.py2 -d sf /bin/bash`
1. _Empty FilesDB_: `sudo touch /var/lib/eopkg/info/files.db && time ./eopkg.py2 -d sf /bin/bash`
1. _Corrupt FilesDB_: `sync && echo "0xDEADBEEF" | sudo tee /var/lib/eopkg/info/files.db && sync && time ./eopkg.py2 -d sf /bin/bash`
1. _Unversioned bsddb FilesDB_: `sudo rm /var/lib/eopkg/info/files.db* …
=> py2 LazyDB/FilesDB: Use pickle protocol v2, write gdbm-backed shelve, set FILESDB_FORMAT_VERSION = 3

pisi/index.py
Will make the index operation slightly more verbose, but also show the user which packages were added for a build, which is IMO a net benefit.
Example:
sudo ./eopkg.py3 index --skip-signing /var/lib/solbuild/local/ --output /var/lib/solbuild/local/eopkg-index.xml
Building index of eopkg files under /var/lib/solbuild/local/
Adding packages to index:
solbuild-config-local-unstable-1.7.0-55-1-x86_64.eopkg
eopkg-4.1.5-17-1-x86_64.eopkg
python-eopkg-4.1.5-17-1-x86_64.eopkg
ypkg-33-195-1-x86_64.eopkg
pisi-3.12.5-118-1-x86_64.eopkg
solbuild-1.7.0-55-1-x86_64.eopkg
solbuild-config-unstable-1.7.0-55-1-x86_64.eopkg
Index file written
=> index: Show packages added on their own lines

pisi/archive.py
Fixes issues with Sublime Text (3rd-party) build
Part of https://github.com/getsolus/3rd-party/issues/78
Fixes this error:
```
<class 'ValueError'>: Cannot specify a preset compression level when opening a file for reading
Please use 'eopkg help' for general help.
Traceback:
File "/usr/bin/eopkg.py3", line 8, in <module>
sys.exit(main())
^^^^^^
File "/usr/lib/python3.11/site-packages/pisi/scripts/eopkg.py", line 78, in main
cli.run_command()
File "/usr/lib/python3.11/site-packages/pisi/cli/pisicli.py", line 131, in run_command
self.command.run()
File "/usr/lib/python3.11/site-packages/pisi/cli/build.py", line 209, in run
pisi.api.build(x)
File "/usr/lib/python3.11/site-packages/pisi/api.py", line 954, in build
return pisi.atomicoperations.build(*args, **kw) …
```
=> Don't set compression level when opening an lzma archive for reading

pisi/cli/index.py
This option either needs to be documented or deprecated. Documenting is easier in this case.
Closes #110.
=> CLI/index: Add valid compression types to help string

dist/man/eopkg.1, dist/man/eopkg.1.md, pisi/cli/command.py, pisi/fetcher.py, pisi/uri.py
This completely removes support for authenticating to eopkg repositories using HTTP Basic-Auth. 
Closes #108.
1. This isn't something we use or have any reason to use officially.
2. No one on the team has a worthwhile test case for this functionality.
3. `eopkg` has an abundance of features which are rarely or never used, and the codebase is very difficult to maintain. Removing unused or impractical non-features such as this reduces code complexity and test surface area.
1. Check out this PR.
2. Try `eopkg --username=someuser <command>` and note that you now receive an error.
3. Do the same test with `--password` and the shorthand arguments `-p` and `-u`.
4. Try some basic operations requiring fetches from the server (install, remove, update, fetch, etc.) normally and see that they still …
=> Remove HTTP Basic-Auth repository support

pisi/atomicoperations.py
When upgrading a package creates file conflicts, we need to check that the conflicting package is also slated for upgrade. In that case, we can be reasonably certain that the conflict isn't an actual problem (see 7895e0b for details). 
The current operational issue with this code is that it if a package has N file conflicts, we make N calls to `pisi.api.list_upgradable()`. That call is very intensive, causing the upgrade operation to take a very, very long time and cause extremely heavy load on system resources. If we move the call to `pisi.api.list_upgradable` out of the inner for loop, we can make that call only once per *package containing file conflicts*, rather than once per *conflicting file*. The list of upgradable packages won't change while we're in the process of installing a …
=> Move call to list_upgradable out of inner loop

pisi/atomicoperations.py
Python 3 eopkg versions crash badly if a package has a malformed `version` string, such as `3.0.0d`. While we don't want versions formatted like that, it shouldn't crash eopkg completely. 
This PR makes that case an error (to alert packagers testing it to the issue), but allows package installation to succeed.
For context, the reason that we're making this case an error is that people on older eopkg 4.x versions will still experience an eopkg crash with a cryptic error message if they encounter malformed version strings.
=> Avoid a nasty crash if a package has a malformed version string

pisi/cli/help.py
I'm fairly certain that we need to force-import all of these or help is truncated due to how `pisi.command.autocommand` is written.
My guess is that this (or a nearly identical strategy) worked in python2 because of differently-optimized processing and ordering of imports. I think perhaps the python3 interpreter only loads up to the code it's actually running when importing a large module (like `pisi.cli`, for example), and in effect doesn't know about code it's never going to call.
In any case, importing all the things *does* fix the problem.
In the future, I would ideally like to rip out all of this stuff and massively refactor `pisi.cli`, but we're stuck with this *very* python2-ish `optparse` hackery for now. Big refactoring efforts are going to have to wait until the current …
=> pisi.cli.help: Import all commands that sort alphabetically after help

pisi/cli/build.py
This is possibly an overly ham-fisted approach to solving #49. I think that some of the dynamic import stuff inside eopkg's build code just doesn't work in nuitka. I think there's a way to compile programs in a hybrid mode which would run certain pieces of the program as interpreted, which may fix this, but that seems like a lot of work just for a feature whose main purpose (3rd party) deprecated and will be removed. 
**Test Plan**
1. Build and install the `eopkg` package using this PR.
2. Run `eopkg.bin bi`. Note the error and exit.
3. Run `eopkg.py3 bi`. Note the different error (lacking a file to build). This proves that the PR is working. The check being done will stop all `build` operations using a compiled version of eopkg, while operations using interpreted `eopkg` are unaffected.
=> pisi.cli.build: Fail with a readable error when attempting to build packages using a compiled eopkg

pisi/index.py
=> index: Only show each package added to index if --verbose

pyproject.toml
Fix the deprecated license declaration format by adjusting it to PEP 639
Fixes the following deprecation warning:
```
/usr/lib/python3.12/site-packages/setuptools/config/_apply_pyprojecttoml.py:82: SetuptoolsDeprecationWarning: `project.license` as a TOML table is deprecated
!!
********************************************************************************
Please use a simple string containing a SPDX expression for `project.license`. You can also use `project.license-files`. (Both options available on setuptools>=77.0.0).
By 2026-Feb-18, you need to update your project and remove deprecated calls
or your builds will no longer be supported.
See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details. …
```
=> Fix deprecated license declaration format

eopkg.py3
Tiny little change. Rationale: 
- If you're debugging, you probably want to see a traceback.
- If you're debugging, there is quite possibly nothing more frustrating than "**Program Terminated.**" with no further errors even when `--debug` is specified.
There may be a more elegant way to handle this, but that's going to be a problem for another day.
=> eopkg.py3.handle_exception: Show traceback on `pisi.Error` (not just on `pisi.Exception`) if `--debug` is specified.

pisi/atomicoperations.py
Previously, if a file known to PiSi as a config file was removed before the `remove` operation started, `eopkg` would crash with an ugly error, potentially leaving the system in a broken state. The problem originates with a logic fault - most already-removed files simply result in warnings when their package is removed. However, checking that the file exists, we check to see if a file is a configuration file. If it is, we check the hash to see if the file was changed after installation. **This hash comparison fails** if the file does not exist. The remove operation checks for `pisi.FileError`, but *not* `pisi.FileNotFoundError` when comparing the file hash. If the file is not found, the resulting exception is not caught, and `eopkg` crashes.
This PR adds proper exception handling for …
=> atomicoperations: Warn when attempting to remove a deleted config file

pisi/db/filesdb.py
**Summary**
Note that this needs the pot file to be updated, which already has to be done anyways. Let's do that in a separate PR.
Fixes https://github.com/getsolus/eopkg/issues/130
**Test Plan**
Tested by updating the pot file, and running `sudo ./eopkg.py3 rdb`.
=> filesdb: Fix localization formatting

pisi/db/repodb.py
Fix an issue where `add-repo` would crash when adding a repository that exists, but was deactivated.
Resolves #149
=> pisi: Fix crash when adding a deactivated repo

pisi/cli/check.py
Changes the message 
> Pisi was unable to check the integrity of packages which contain files that you don't have read access. 
> Running the check under a privileged user may help fixing this problem.
to 
> Could not check the integrity of packages which contain files your user did not have permission to read.
> Running the check under a privileged user may help to fix this problem.
Fixes #138.
=> pisi.cli.check: Rewrite warning to not reference Pisi

pisi/api.py, pisi/cli/fetch.py, pisi/cli/info.py, pisi/cli/install.py, pisi/cli/listavailable.py, pisi/cli/listcomponents.py, pisi/cli/listnewest.py, pisi/cli/listupgrades.py, pisi/cli/search.py, pisi/cli/searchfile.py, pisi/cli/upgrade.py
**Summary**
Some commands require an active repository to be configured on the system in order to be able to function. If no repositories are configured, they may fail silently, or in other unexpected ways. This solves that issue by adding an API function to check for the presence of active repositories, and having the CLI bail with a message if none are found.
This may not encompass the entire list of commands that need to check for repositories, but at least it's a good start.
Ref https://github.com/getsolus/eopkg/issues/106
**Test Plan**
Disable all repositories on my system, and try to search for packages.
=> api,cli: Add checking for active repositories

dist/man/eopkg.1, dist/man/eopkg.1.md, pisi/cli/listinstalled.py
**Summary**
This adds an option to the `list-installed` command to list only packages that were explicitly installed by a user of the system. The manpage was re-generated accordingly.
Fixes https://github.com/getsolus/eopkg/issues/126
**Test Plan**
Run `./eopkg.py3 list-installed --explicit`. I have a crapton of manually installed packages on my system as a result of compiling various software, so it's extremely hard for me to tell if a package was truly installed by me or not.
=> list-installed: Add option for explicitly installed packages

pisi/__init__.py, pisi/api.py, pisi/atomicoperations.py, pisi/cli/history.py, pisi/context.py, pisi/operations/install.py, pisi/operations/remove.py, pisi/operations/upgrade.py, pisi/signalhandler.py
This refactors the Pisi signal handler to be easier to follow. I'm not actually sure it was ever working correctly before. I'm not sure if we really need or want to hold pending signals to emit later, but I kept that functionality, while providing a way to disable it.
As a part of this, we now disable keyboard interrupts (SIGINT) for more operations: rebuild-database, remove package, and update repos.
Fixes https://github.com/getsolus/eopkg/issues/141
Fixes https://github.com/getsolus/eopkg/issues/105
- Run `./eopkg.py3 history`, hit Ctrl+C, and see that the interrupt message no longer prints.
- Run `./eopkg.py3 rdb`, hit Ctrl+C, and see that the process is not interrupted until the rebuild finishes.
More testing is definitely required, but the other operations usually happen too fast for …
=> signalhandler: Refactor signal handling

dist/completions/bash/eopkg, dist/completions/zsh/_eopkg
**Summary**
The Bash completions are just copied over from our `bash-completions` package. The ZSH completions, on the other hand, were handwritten from scratch. What a journey. Some of the completions are a bit slow, but I don't know enough about the completion system to speed it up, and after spending an afternoon on it, it's become a problem for a later date.
There are no Fish completions because `eopkg` completions were submitted upstream [to the Fish project many years ago](https://github.com/fish-shell/fish-shell/blob/master/share/completions/eopkg.fish), and so are distributed by Fish. Not sure what, if anything, we want to do about that right now.
Fixes https://github.com/getsolus/eopkg/issues/118
**Test Plan**
1. Install the new completion files.
```bash
sudo cp …
```
=> dist: Add bash and zsh completions

pisi/util.py
Fixes a misplaced import introduced in #170.
1. Remove `python-jeepney` from your system.
2. Ensure your system is fully updated, running `python-eopkg` rel 26.
3. Try `lseopkg <some-eopkg-file>`.
4. Note the failure to import `jeepney`.
5. Create a venv in your clone of this repository with this PR checked out. Make sure that `jeepney` is not installed in the venv (`pip uninstall jeepney`).
6. Try `./pisi/scripts/lseopkg.py <some-eopkg-file>` and note that it works.
Partially fixes https://github.com/getsolus/packages/issues/6165.
=> pisi.util: Fix import in the wrong place, remove unnecessary import

pyproject.toml
Adds `ordered_set` to build deps.
1. Attempt to build an `eopkg` wheel (I did it with `pip install .`).
2. Notice that it doesn't work.
3. Check out this PR.
4. `pip install .`.
5. It works!
=> pyproject.toml: Add ordered_set to build requirements

pyproject.toml
Follow-up to https://github.com/getsolus/eopkg/pull/182
Install `ypkg` and `eopkg` in a venv and run `ypkg` without an error about `ordered_set` missing.
=> pyproject: Add ordered_set to dependencies
